# Generated by Django 5.2.7 on 2025-11-15 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_bookmark_readinganalytics_readingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_topics', models.JSONField(default=list)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_documents', models.ManyToManyField(blank=True, to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_times', models.JSONField(default=list)),
                ('avg_session_duration', models.IntegerField(default=0)),
                ('preferred_content_types', models.JSONField(default=list)),
                ('reading_streak', models.IntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('common_themes', models.JSONField(default=list)),
                ('document1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_from', to='documents.document')),
                ('document2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to='documents.document')),
            ],
            options={
                'unique_together': {('document1', 'document2')},
            },
        ),
    ]
