# Generated by Django 5.2.7 on 2025-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reading_mode',
            field=models.CharField(choices=[('direct', 'Direct Read'), ('story', 'Story Read')], default='direct', max_length=20),
        ),
    ]
