# Generated by Django 5.2.7 on 2025-10-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(default=list)),
                ('preferred_reading_mode', models.CharField(choices=[('direct', '📄 Direct Read'), ('story', '📖 Story Read')], default='direct', max_length=20)),
                ('reading_level', models.CharField(choices=[('casual', '😊 Casual'), ('detailed', '🎯 Detailed'), ('academic', '📊 Academic')], default='casual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
